### ISSUE TITLE
Where is the API "auth/token" ?

### ISSUE THREAD

**Issue by lookphp** [tecnom1k3/sp-simple-jwt#13]
when i click sign in , it return error , and i can't find it in public directory . Thank you !

**Comment by lookphp** [comment]
I have solve it , to replace login.php for auth/token but there is another question . 
in resource.php file line 39,
$asset = base64_encode(file_get_contents('http://lorempixel.com/200/300/cats/'));

i don't know the url's mean .

**Comment by technotenshi** [comment]
The article was written some time ago, so it needs apache + mod_rewrite to
work

**Comment by FazilaMehtab** [comment]
How to do this  apache + mod_rewrite because I am having the same issue.

**Comment by FazilaMehtab** [comment]
@lookphp have you resolve that issue?

**Comment by lookphp** [comment]
I have no idea , my project didn't use it . I'm so sorry . @FazilaMehtab , you can ask @tecnom1k3 for help .

**Comment by technotenshi** [comment]
I will create a separate branch that will not require server url rewrite, so you can test there. I can not really touch the main branch in order to not disrupt the article itself.  I have to find some time to do this, so please I ask to be patient.  thanks

**Comment by technotenshi** [comment]
got rid off the rewrites, plus added the possibility to use docker to run the application
