### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by ghost** [tecnom1k3/sp-simple-jwt#14]
The web server (apache 2.4.23 with rewrite_mod, php 7.0.10) is unable to find /public/auth/token

Any suggestion ?

Thanks

**Comment by technotenshi** [comment]
yes this code is a little old.  Guess I'll remove the rewrite rules, but in
the meantime you can link directly to the public/login.php and
public/resource.php directly in the public/js/main.js file instead of the
rewrites.

2017-11-17 2:43 GMT-08:00 npierluigi <notifications@github.com>:

**Comment by technotenshi** [comment]
fixed the above, plus took the opportunity to be able to use docker to run the application
